### PR TITLE
swift 4 migration

### PR DESCRIPTION
**Pull request by irshadpc**
swift 4 migration

### CODE REVIEW

**Comment by rushisangani** [comment]
Minimum deployment target could not be set to iOS 11.
It won't work with iOS 10.

**Comment by irshadpc** [comment]
@rushisangani We can release separate framework for swift 3 and swift 4. If you like i will do for the same.

**Comment by rushisangani** [comment]
I would happy to do that.
But I am curious to know, which version should I update in Cocoapods - support for Swift 3.2 or 4.0
I guess we can't support both simultaneously using same cocoa pod version.

**Comment by irshadpc** [comment]
@rushisangani Do the versioning for swift 3 and swift 4 on pod spec.

**Comment by rushisangani** [comment]
@irshadpc could you please do the necessary setup and framework changes to support both swift 3 and 4.
I would happy to merge your pull request.
Also, please provide what should be done in podspec file to support both versions.

**Comment by irshadpc** [comment]
@rushisangani Check this https://github.com/CocoaPods/CocoaPods/issues/6791

**Pull request closed without merging**
