### PR TITLE
Swift Package Manager

### PR DESCRIPTION
**Pull request by basvankuijck**
Future releases should be tagged like so: `v3.1.2`

### CODE REVIEW

**Comment by rushisangani** [comment]
@basvankuijck Thanks for the PR.
What do I do, after merging this PR?
Do I need to release a new versions?

**Comment by basvankuijck** [comment]
You need to tag it with `v3.1.1` (the "v" is very important for SwiftPM)

**Comment by rushisangani** [comment]
@basvankuijck I can merge this PR.
Thanks for the support.

Just let me know, do I need to release a new version in cocoapods?

**Comment by basvankuijck** [comment]
@rushisangani : No that's not necessary.
I only updated the podspec so that he aligns with the SwiftPM (git tag) version

**Comment by rushisangani** [comment]
@basvankuijck I just created a new release.
https://github.com/rushisangani/BiometricAuthentication/releases/tag/v3.1.1

I hope this is correct.

**Pull request merged**
